Plug 'kien/ctrlp.vim'
Plug 'neovimhaskell/haskell-vim'
Plug 'eagletmt/neco-ghc'
Plug 'benekastah/neomake'
Plug 'bling/vim-airline'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdtree'
Plug 'majutsushi/tagbar'
Plug 'rking/ag.vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'jeetsukumaran/vim-buffergator'

Plug 'leafgarland/typescript-vim'
Plug 'raichoo/purescript-vim'
Plug 'lambdatoast/elm.vim'
Plug 'derekwyatt/vim-scala'
