templates:
  params:
    author-name: CristhianMotoche
    author-email: cristhian.motoche@gmail.com
    copyright: WTFPL
    github-username: CristhianMotoche

nix:
  enable: false
  packages: [zlib.dev, zlib.out]
